#argo-manifest.yml file
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: bank-app
  namespace: argocd
spec: 
  project: default
  source: 
    repoURL: https://github.com/lateef-taiwo/Bank_App_Kube_Manifest  
    targetRevision: HEAD
    path: manifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: bank-app
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true 
